Program ::= Expr
Expr    ::= Const
          | Diff
          | Zero
          | If
          | Var
          | Let
Const   ::= Number
Diff    ::= '-' '(' Expr ',' Expr ')'
Zero    ::= 'zero?' '(' Expr ')'
If      ::= 'if' Expr 'then' Expr 'else' Expr
Var     ::= Id
Let     ::= 'let' (Id '=' Expr)+ 'in' Expr
Number  ::= [0-9]+
Id      ::= [a-z]+

/* Use https://www.bottlecaps.de/rr/ui to view it as a Railroad Diagram. */
